### ISSUE TITLE
Pick up health orbs

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#100]
Needs to be subtle. Kingdom Hearts does this well.

**Comment by ghost** [comment]
We need to find a way to limit the number of times this can play when you pick up 20+ health orbs at once.  It balloons in volume and starts clipping during fights in the fort, even after turning it down so low you can't hear it when there's only 1

**Comment by gap9269** [comment]
That won't be hard to do

**Comment by ghost** [comment]
Made an alternate version that hopefully won't stack up on itself quite as much, because I found the sound getting really annoying after hearing it too many times. Limiting # of playbacks/volume might make it a non-issue though, so keeping both sounds around.
