### ISSUE TITLE
Pick up coins

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#101]
I think the one we have is pretty good, but it has a weird humming in the background. Plus I think I stole it.

**Comment by gap9269** [comment]
They sound clipped, almost. I'll get your opinions on it

**Comment by ghost** [comment]
They were way louder than intended.  I turned it down a lot, and it sounds way better.  You may still want something longer but I made it short because of how many you are likely to hear at a time during bigger fights in the fort and such. See how you like it at the proper volume.
