### ISSUE TITLE
Gorilla Tim Fight

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#119]

**Comment by gap9269** [comment]
Some of these sounds are kind of loud and distorted-sounding. Especially the barrels and fist/foot steps.

**Comment by ghost** [comment]
softened the footsteps a bit. not sure about the barrels though they're just filtered noise and theyre supposed to sound all crappy and retro

**Comment by ghost** [comment]
Gonna Re-do Tim's footsteps, they sound all muddy and gross
