### ISSUE TITLE
Sword Barrage

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#121]

**Comment by ghost** [comment]
Made different sounds for each level because the animation changes so drastically in length. Will need variations of each at some point.

**Comment by gap9269** [comment]
These need to be split up into the separate swings, or at least into parts. Because there are slight pauses when you hit enemies the animation is actually shorter than the sound clips for levels 3 and 4 (if you swing and don't hit anything).

**Comment by ghost** [comment]
So this gets confusing... I split each lvl into parts labelled A-D in order. lvls 1 and 2 have 3 parts, 3 and 4 both have 4.  You trigger A at the beginning of the skill, B right on the beginning of the second swing, etc.

'A' might sound weird on its own because it keeps going for a while, but that's because it had some layers of whipping sounds that don't sync to anything and just make it more chaotic.  Since those get triggered at the beginning, it's ok if it just keeps going regardless of the timing of the other parts.
