### ISSUE TITLE
Anubis - prepare skill

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#122]

**Comment by ghost** [comment]
This is when Anubis raises his staff to either cast the shockwave or the locust abilities.

**Comment by gap9269** [comment]
I thought the "summon" sound was for that?

**Comment by ghost** [comment]
yes, but I didn't hear it in-game so i figured it wasn't implemented yet
because I wasn't clear or something.

On Fri, Feb 13, 2015 at 12:44 PM, Gary notifications@github.com wrote:

> I thought the "summon" sound was for that?
> 
> On Fri, Feb 13, 2015 at 3:13 PM, Miles Flanagan notifications@github.com
> wrote:
> 
> > This is when Anubis raises his staff to either cast the shockwave or the
> > locust abilities.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gap9269/SDDSound/issues/122#issuecomment-74318986.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/122#issuecomment-74323792.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by ghost** [comment]
Actually I looked through the video more and it's there, it just failed to play a couple of times.
