### ISSUE TITLE
Idea for handling music between maps

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#124]
Load all music for a map zone as you enter one of the maps. So when you enter the "Intro To Science" room, it loads all science tracks. This way I can pause and play and stop and whatever I need to do between maps, without having to start songs over.

Additionally, there should be a "Base Background Volume" that represents the current volume setting. I can use that value to fade music in and out when I need to. Same for ambience.

**Comment by ghost** [comment]
That sounds like it should work. What happens when you go to a map with
different music? (eg science 101 -> hallway) do they crossfade?  Should you
load all the tracks associated with a set of maps and also the ones
connecting to it?

On Mon, Feb 16, 2015 at 3:29 PM, Gary notifications@github.com wrote:

> Load all music for a map zone as you enter one of the maps. So when you
> enter the "Intro To Science" room, it loads all science tracks. This way I
> can pause and play and stop and whatever I need to do between maps, without
> having to start songs over.
> 
> Additionally, there should be a "Base Background Volume" that represents
> the current volume setting. I can use that value to fade music in and out
> when I need to. Same for ambience.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/124.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by gap9269** [comment]
One fades out, unloads, new stuff loads then fades in.

**Comment by ghost** [comment]
So there's a gap of silence where stuff is loading in/out? That might still
be ok when moving between distinct areas, though.

On Mon, Feb 16, 2015 at 4:42 PM, Gary notifications@github.com wrote:

> One fades out, unloads, new stuff loads then fades in.
> 
> On Mon, Feb 16, 2015 at 7:31 PM, Miles Flanagan notifications@github.com
> wrote:
> 
> > That sounds like it should work. What happens when you go to a map with
> > different music? (eg science 101 -> hallway) do they crossfade? Should
> > you
> > load all the tracks associated with a set of maps and also the ones
> > connecting to it?
> > 
> > On Mon, Feb 16, 2015 at 3:29 PM, Gary notifications@github.com wrote:
> > 
> > > Load all music for a map zone as you enter one of the maps. So when you
> > > enter the "Intro To Science" room, it loads all science tracks. This
> > > way
> > > I
> > > can pause and play and stop and whatever I need to do between maps,
> > > without
> > > having to start songs over.
> > > 
> > > Additionally, there should be a "Base Background Volume" that
> > > represents
> > > the current volume setting. I can use that value to fade music in and
> > > out
> > > when I need to. Same for ambience.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gap9269/SDDSound/issues/124.
> > 
> > ## 
> > 
> > Miles Flanagan
> > Composer, Sound Designer for Games
> > milesflanaganmusic.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gap9269/SDDSound/issues/124#issuecomment-74596335.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/124#issuecomment-74598292.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by gap9269** [comment]
I think it will be fine
