### ISSUE TITLE
Pick up Textbooks

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#135]

**Comment by gap9269** [comment]
Perhaps #133, #134, and this are all the same sound.

**Comment by ghost** [comment]
there are sounds for these in the locker ui. See if these work.

On Sun, Apr 5, 2015 at 10:26 PM, Gary notifications@github.com wrote:

> Perhaps #133 https://github.com/gap9269/SDDSound/issues/133, #134
> https://github.com/gap9269/SDDSound/issues/134, and this are all the
> same sound.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/135#issuecomment-89928398.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by gap9269** [comment]
They might, but I have a feeling we'll want something flashier for these
pop-ups. I'll try them out soon

**Comment by ghost** [comment]
I see what you mean

On Sun, Apr 5, 2015 at 10:58 PM, Gary notifications@github.com wrote:

> They might, but I have a feeling we'll want something flashier for these
> pop-ups. I'll try them out soon
> 
> On Mon, Apr 6, 2015 at 1:35 AM, Miles Flanagan notifications@github.com
> wrote:
> 
> > there are sounds for these in the locker ui. See if these work.
> > 
> > On Sun, Apr 5, 2015 at 10:26 PM, Gary notifications@github.com wrote:
> > 
> > > Perhaps #133 https://github.com/gap9269/SDDSound/issues/133, #134
> > > https://github.com/gap9269/SDDSound/issues/134, and this are all the
> > > same sound.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/gap9269/SDDSound/issues/135#issuecomment-89928398
> > > .
> > 
> > ## 
> > 
> > Miles Flanagan
> > Composer, Sound Designer for Games
> > milesflanaganmusic.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gap9269/SDDSound/issues/135#issuecomment-89931831.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/135#issuecomment-89936350.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com
