### ISSUE TITLE
Ethereal Ambience

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#150]

**Comment by gap9269** [comment]
Too loud and windy/thunderous.

**Comment by ghost** [comment]
Made it louder than needed since we can turn it down in the engine but not
up. same goes for the other new sounds.  This is meant to be barely audible
so it's going to sound wrong until I edit the vol file.

On Mon, May 11, 2015 at 9:23 PM, Gary notifications@github.com wrote:

> Too loud and windy/thunderous.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/150#issuecomment-101125022.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by gap9269** [comment]
I turned it down to .3. I'll let you mess with it

**Comment by ghost** [comment]
Sounds like you're using the wasteland ambience for the ethereal room right now.  There should be no thunder in it.

**Comment by gap9269** [comment]
Interesting. I'll take a look

**Comment by gap9269** [comment]
Might be too quiet, hard to tell because boston is loud as hell right now

**Comment by ghost** [comment]
is it still turned down to .3?  It might still be too quiet but just
checking

On Tue, Jul 21, 2015 at 5:12 PM, Gary notifications@github.com wrote:

> Might be too quiet, hard to tell because boston is loud as hell right now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/150#issuecomment-123514066.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com
