### ISSUE TITLE
Vent puzzle room ambience

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#163]

**Comment by gap9269** [comment]
This doesn't really sound like the steam is on

**Comment by ghost** [comment]
At some point I'd like to try using a multisound for the steam vents, at least these ones.

It treats the sound as one emitter with multiple positions, and it interpolates all the positions so it sounds like it's coming from all of them but it's only one file playing.  I'd have to make a separate event for start and stop sounds that doesnt also start the loop.  You basically just pass all the locations together as an array.
