### ISSUE TITLE
Clay Enemies

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#171]

**Comment by ghost** [comment]
each attack has 3 parts - form, strike/crash, and reform.  

The animation sync on the 'reform' bits might be tricky because its hard to see where the attack ends and the reform begins but I felt I had to split it since it can be interrupted so easily.  Also, form/reform are way louder than they probably need to be so if they sound weird at first that's why.

**Comment by gap9269** [comment]
Maybe add a smack sound for when the hammer hits the ground? Other than that, I like it.

**Comment by ghost** [comment]
hammer_strike should be a smacky kinda hit sound.  It seems quiet now, it should be way louder the form/reform.
