### ISSUE TITLE
Reverbs

### ISSUE THREAD

**Issue by ghost** [gap9269/SDDSound#242]

**Comment by ghost** [comment]
2 things you need to do to make reverb work:

-call "Enable_Reverb" event to unmute the bus (can call "Mute_Reverb" to turn it back off)

-call Wwise.SetBusEffect(uint fxId) to change to a different type of reverb.  fxId is a 10-digit # for each preset that is detailed in global.txt under Effect plug-ins.  I had to do it this way or I'd have to push a new SDK build every time I added a reverb setting.

current reverb ID's: 
3854292571    Vents  (wide, metallic, claustrophobic)
3888786832    City (short, subtle, reflections give feeling of open space/high walls/alleys)
3999320713    Science (weird/abstract/unnatural sound)
4122393694    Cave (long-ass tail)

Probably just save the numbers as global variables, I don't think the #'s change unless I change the name or something.  Most maps would still have no reverb, only way you can turn it off is by calling the mute event above, but calling mute or enable multiple times wont hurt so you can just call them every transition using a simple conditional (does this get reverb?).  It's also ok to set the bus effect to the same type, it won't break anything.  Reverb is cut off when you switch to another type, but if that only happens during map transitions, that's fine.

Should note that it will probably make everything sound real bad at first, I need to figure out how much to use and what kinds of sounds get how much.

**Comment by gap9269** [comment]
I...think I added this? I can't really tell because the vents and science are already echo a lot

**Comment by ghost** [comment]
It should be noticeable on objects, enemies, and skills.  I'll play with the send levels when I get the build.

The City type is really subtle if you used it.  I was thinking it could be useful in the Quad, Vienna, and whatever that city streets map is, but it's barely noticeable as is.
