### ISSUE TITLE
Troll Attack

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#35]

**Comment by gap9269** [comment]
I think this needs to be split into 2 parts because it can be interrupted. Making it the initial swing noise and then the club colliding should work.

**Comment by ghost** [comment]
split into ready_swing and club_hit

**Comment by ghost** [comment]
I think you're still using the troll_attack sound in the new build

**Comment by gap9269** [comment]
I am. I haven't changed it yet
