### ISSUE TITLE
Door Open

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#41]

**Comment by gap9269** [comment]
Obviously this won't work for every portal in the game. It works for doors. I'm not sure if it's too loud and lengthy, though. Maybe a more subtle noise would work better. Let's discuss

**Comment by ghost** [comment]
Definitely use the portal_enter sound.  It's much more general than at least the door sound.

**Comment by gap9269** [comment]
I'll probably just make the portals take a generic sound then let it be overridden
