### ISSUE TITLE
Load Game

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#59]

**Comment by gap9269** [comment]
I was wrong about this one. I think it needs the ass end of a toilet flush noise, with the door opening at the end of that sound. I think you'll see what I mean when you load a game.

**Comment by gap9269** [comment]
2/1 Updated Sound: Maybe it would make more sense for the door sound to be at the very beginning, since Daryl has already stepped out of the stall, so to speak. Thoughts on this? (I can get you a new build with this sound soon)

**Comment by ghost** [comment]
Put the door at the beginning of the sound, re-uploaded
