### ISSUE TITLE
Text Message

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#61]

**Comment by gap9269** [comment]
Instead of a vibrate let's do a really cliche ringtone beep of some sort. Open to suggestions here

**Comment by ghost** [comment]
Balto now has a cheezy default ringtone. Left the vibrate in there but can take that out if you think it sounds weird.

**Comment by gap9269** [comment]
This has weird music in the background. Was that intentional?

**Comment by ghost** [comment]
That was a really stupid bouncing error and I'll edit it right now.

On Mon, May 11, 2015 at 9:30 PM, Gary notifications@github.com wrote:

> This has weird music in the background. Was that intentional?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/61#issuecomment-101126745.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com
