### ISSUE TITLE
UI - Text Advance

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#65]

**Comment by gap9269** [comment]
Too loud. Sound like gun shots, especially when sped up.

**Comment by ghost** [comment]
Oh, misunderstanding here. This wasn't meant to play while the text is being written, it was for when you press enter to go to the next page of text.  I'm not a fan of text scrolling sounds because they get annoying fast but I'll make a quiet one to try out.

**Comment by gap9269** [comment]
Thanks makes a lot more sense. I don't think we need a scrolling text sound.
