### ISSUE TITLE
Student Locker - Click Dial

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#75]

**Comment by gap9269** [comment]
_03 has two click sounds and it doesn't sound right. I got rid of it in game for now. I doubt we even need to replace it...5 is enough.

**Comment by ghost** [comment]
That's why we try these things out in context, good catch. It totally
doesn't pop out as weird on its own.

On Tue, Jan 6, 2015 at 10:08 PM, Gary notifications@github.com wrote:

> _03 has two click sounds and it doesn't sound right. I got rid of it in
> game for now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/75#issuecomment-68982882.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com
