### ISSUE TITLE
Alarm sound for when enemies are alerted in fort

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#91]

**Comment by ghost** [comment]
Is this like a looping alarm or is it more of a stinger.  Thinking big huge warhorn and/or bells

**Comment by gap9269** [comment]
Just a one-off sound. Probably a warhorn

**Comment by gap9269** [comment]
It needs to be louder and more...obvious? Something that doesn't fit in so well with the ambience. It's the only indication that the player has that enemies will start spawning like crazy now...aside from them starting to spawn like crazy.

**Comment by ghost** [comment]
I'll make it so much louder

On Monday, February 2, 2015, Gary notifications@github.com wrote:

> It needs to be louder and more...obvious? Something that doesn't fit in so
> well with the ambience. It's the only indication that the player has that
> enemies will start spawning like crazy now...aside from them starting to
> spawn like crazy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/91#issuecomment-72562056.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by ghost** [comment]
made it a little louder, added huge-ass war drums
