### ISSUE TITLE
Level Up 

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#95]
No idea for this one. Maybe a crazy guitar riff and explosion sounds?

**Comment by ghost** [comment]
That's what i like to hear

On Wed, Jan 7, 2015 at 10:15 AM, Gary notifications@github.com wrote:

> No idea for this one. Maybe a crazy guitar riff and explosion sounds?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gap9269/SDDSound/issues/95.

## 

Miles Flanagan
Composer, Sound Designer for Games
milesflanaganmusic.com

**Comment by gap9269** [comment]
Not sure what to think of this one yet
