### ISSUE TITLE
Skill Level Up 

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#96]
We have the sliding pop-up sound for the box's movement, but I think we need a sound to indicated a skill leveling up. I'm not sure what it should be just yet

**Comment by gap9269** [comment]
Might need to be a bit louder and longer. It was hard to notice in Science

**Comment by ghost** [comment]
So this plays 4 times simultaneously if all the skills level up at the same time and that's bad

**Comment by gap9269** [comment]
Hmmmmm.
I can fix this

**Comment by gap9269** [comment]
Do we want to revisit this? They don't stack anymore.

**Comment by ghost** [comment]
Want to leave it for a little while and get used to it now that it plays correctly.  Still unsure about it stylistically
