### ISSUE TITLE
Player Ducking

### ISSUE THREAD

**Issue by gap9269** [gap9269/SDDSound#97]

**Comment by gap9269** [comment]
Loud and kind of...raspy? Not sure how to describe it. I'll let you check it out when you play.

**Comment by ghost** [comment]
These were also way too loud.  Way better now that I turned it down. Supposed to be just a subtle little squeaky, rustley thing that you wouldn't even notice if much else was going on.

**Comment by gap9269** [comment]
I still think this is kind of distorted sounding, almost crunchy.
